# Generated by Django 5.0.14 on 2025-12-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('cta_click', 'CTA Button Click'), ('share_instagram', 'Share to Instagram'), ('share_facebook', 'Share to Facebook'), ('share_twitter', 'Share to Twitter/X'), ('share_copy_link', 'Copy Link'), ('share_native', 'Native Share'), ('rsvp_interested', 'RSVP Interested'), ('rsvp_going', 'RSVP Going'), ('form_open', 'Form Opened'), ('form_submit', 'Form Submitted'), ('directions_click', 'Directions Clicked'), ('website_click', 'Website Clicked'), ('instagram_click', 'Instagram Profile Clicked'), ('tiktok_click', 'TikTok Profile Clicked')], max_length=30)),
                ('page_type', models.CharField(choices=[('event', 'Event Page'), ('business', 'Business Page')], max_length=20)),
                ('object_id', models.IntegerField(help_text='ID of the event or business')),
                ('session_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional interaction data (e.g., clicked URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('event', 'Event Page'), ('business', 'Business Page')], max_length=20)),
                ('object_id', models.IntegerField(help_text='ID of the event or business')),
                ('session_id', models.CharField(help_text='Anonymous session identifier for unique visitor counting', max_length=64)),
                ('referrer', models.URLField(blank=True, help_text='HTTP referrer URL')),
                ('referrer_type', models.CharField(blank=True, choices=[('direct', 'Direct'), ('social_instagram', 'Instagram'), ('social_facebook', 'Facebook'), ('social_twitter', 'Twitter/X'), ('social_tiktok', 'TikTok'), ('search', 'Search Engine'), ('subdomain', 'Custom Subdomain'), ('internal', 'Internal Link'), ('other', 'Other')], help_text='Categorized referrer source', max_length=30)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('is_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('event', 'Event'), ('business', 'Business')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('date', models.DateField()),
                ('total_views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('mobile_views', models.IntegerField(default=0)),
                ('desktop_views', models.IntegerField(default=0)),
                ('referrer_direct', models.IntegerField(default=0)),
                ('referrer_social', models.IntegerField(default=0)),
                ('referrer_search', models.IntegerField(default=0)),
                ('referrer_subdomain', models.IntegerField(default=0)),
                ('referrer_internal', models.IntegerField(default=0)),
                ('referrer_other', models.IntegerField(default=0)),
                ('cta_clicks', models.IntegerField(default=0)),
                ('share_clicks', models.IntegerField(default=0)),
                ('rsvp_interested', models.IntegerField(default=0)),
                ('rsvp_going', models.IntegerField(default=0)),
                ('form_opens', models.IntegerField(default=0)),
                ('form_submits', models.IntegerField(default=0)),
                ('directions_clicks', models.IntegerField(default=0)),
                ('external_link_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Summary',
                'verbose_name_plural': 'Analytics Summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['page_type', 'object_id', 'date'], name='analytics_a_page_ty_39ad55_idx'), models.Index(fields=['date'], name='analytics_a_date_3f3dc8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='analyticssummary',
            constraint=models.UniqueConstraint(fields=('page_type', 'object_id', 'date'), name='unique_daily_summary'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['page_type', 'object_id', 'created_at'], name='analytics_i_page_ty_7a37ae_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['page_type', 'object_id', 'interaction_type'], name='analytics_i_page_ty_d5120e_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['interaction_type', 'created_at'], name='analytics_i_interac_de3322_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page_type', 'object_id', 'created_at'], name='analytics_p_page_ty_ad57d0_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page_type', 'object_id', 'session_id'], name='analytics_p_page_ty_d3f266_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['created_at'], name='analytics_p_created_4c2b45_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['referrer_type'], name='analytics_p_referre_efcf32_idx'),
        ),
    ]
