# Generated by Django 5.0.14 on 2026-01-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0018_add_business_instagram_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_post_id', models.CharField(help_text="Instagram's unique post ID", max_length=100)),
                ('original_permalink', models.URLField(blank=True, help_text='Link to original Instagram post')),
                ('original_caption', models.TextField(blank=True, help_text='Original caption from Instagram post')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_imports', to='events.business')),
                ('event', models.ForeignKey(blank=True, help_text='The draft event created from this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_source', to='events.event')),
            ],
            options={
                'verbose_name': 'Instagram Post Log',
                'verbose_name_plural': 'Instagram Post Logs',
                'indexes': [models.Index(fields=['business', 'instagram_post_id'], name='instagram_i_busines_e78394_idx'), models.Index(fields=['imported_at'], name='instagram_i_importe_877cde_idx')],
                'unique_together': {('business', 'instagram_post_id')},
            },
        ),
    ]
