# Generated by Django 5.0.14 on 2025-11-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='businesses',
            field=models.ManyToManyField(help_text='Select one or more businesses participating in this event', related_name='events', to='events.business'),
        ),
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select one or more categories (e.g., matcha, coffee, baked goods)', related_name='businesses', to='events.category'),
        ),
    ]
