# Generated by Django 5.0.14 on 2025-11-11 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_remove_event_business_and_more'),
    ]

    operations = [
        # Make business email optional
        migrations.AlterField(
            model_name='business',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        # Make event description optional
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        # Add host business field to events
        migrations.AddField(
            model_name='event',
            name='host_business',
            field=models.ForeignKey(
                blank=True,
                help_text='Primary business hosting this event (optional)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hosted_events',
                to='events.business'
            ),
        ),
        # Make businesses many-to-many optional
        migrations.AlterField(
            model_name='event',
            name='businesses',
            field=models.ManyToManyField(
                blank=True,
                help_text='Select one or more businesses participating in this event',
                related_name='events',
                to='events.business'
            ),
        ),
        # Add optional location name field
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(
                blank=True,
                help_text='Name of the venue/location (optional)',
                max_length=255
            ),
        ),
    ]
