# Generated by Django 5.0.14 on 2025-11-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_business_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='available_for_hire',
            field=models.BooleanField(default=False, verbose_name='Available for Hire'),
        ),
        migrations.AddField(
            model_name='business',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok URL'),
        ),
    ]
