# Generated by Django 5.0.14 on 2025-11-13 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_latitude_alter_event_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('going', 'Going')], help_text='The type of RSVP (interested or going)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='The event the user is RSVPing to', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('user', models.ForeignKey(help_text='The user making the RSVP', on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event RSVP',
                'verbose_name_plural': 'Event RSVPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='events_even_event_i_c5a858_idx'), models.Index(fields=['user', 'created_at'], name='events_even_user_id_adc0a1_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
