# Generated by Django 5.0.14 on 2025-11-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventrsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cta_button_text',
            field=models.CharField(blank=True, help_text="Text for the call-to-action button (e.g., 'Buy Tickets', 'Register Now')", max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='cta_button_url',
            field=models.URLField(blank=True, help_text='URL for the call-to-action button'),
        ),
    ]
