# Generated by Django 5.0.14 on 2025-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_add_event_cta_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='custom_subdomain',
            field=models.SlugField(blank=True, help_text="Custom subdomain for this business (e.g., 'mybusiness' for mybusiness.popmap.co)", null=True, unique=True),
        ),
    ]
