# Generated by Django 5.0.14 on 2025-11-19 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_add_business_custom_subdomain'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_template',
            field=models.ForeignKey(blank=True, help_text='Optional form for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='forms.formtemplate'),
        ),
    ]
