# Generated by Django 5.0.14 on 2025-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_form_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_login_for_rsvp',
            field=models.BooleanField(default=True, help_text='If checked, only registered users can RSVP. If unchecked, anyone can RSVP with an email.'),
        ),
    ]
