# Generated by Django 5.0.14 on 2025-11-26 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_require_login_for_rsvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='gdpr_consent',
            field=models.BooleanField(default=False, help_text='Whether the guest has consented to data processing'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='gdpr_consent_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when GDPR consent was given', null=True),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email for guest RSVPs (when user is not logged in)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Optional name for guest RSVPs', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The registered user making the RSVP (null for guest RSVPs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['guest_email'], name='events_even_guest_e_af744d_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='unique_event_user_rsvp'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_email__isnull', False)), fields=('event', 'guest_email'), name='unique_event_guest_email_rsvp'),
        ),
    ]
