# Generated by Django 5.0.14 on 2025-11-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventrsvp_unique_together_and_more'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='active_form_template',
            field=models.ForeignKey(blank=True, help_text='The form template to display on the business profile page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_businesses', to='forms.formtemplate'),
        ),
    ]
