# Generated by Django 5.0.14 on 2025-11-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_add_business_active_form_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='background_image_url',
            field=models.URLField(blank=True, help_text='URL for custom background image (premium feature)'),
        ),
        migrations.AddField(
            model_name='business',
            name='custom_primary_color',
            field=models.CharField(blank=True, help_text='Custom primary color in hex format, e.g., #FF5733 (premium feature)', max_length=7),
        ),
        migrations.AddField(
            model_name='business',
            name='default_view_mode',
            field=models.CharField(choices=[('map', 'Map View'), ('list', 'List View'), ('card', 'Card View')], default='card', help_text='Default view mode for business page (premium feature)', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='show_upcoming_events_first',
            field=models.BooleanField(default=True, help_text='Show upcoming events before past events (premium feature)'),
        ),
    ]
