# Generated by Django 5.0.14 on 2025-12-06 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_add_business_premium_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event_reminders_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guest Email Preference',
                'verbose_name_plural': 'Guest Email Preferences',
            },
        ),
        migrations.CreateModel(
            name='EventReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('24h', '24 Hours Before'), ('1h', '1 Hour Before')], default='24h', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_to', models.EmailField(max_length=254)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='events.eventrsvp')),
            ],
            options={
                'verbose_name': 'Event Reminder Log',
                'verbose_name_plural': 'Event Reminder Logs',
                'indexes': [models.Index(fields=['rsvp', 'reminder_type'], name='events_even_rsvp_id_653aa4_idx'), models.Index(fields=['sent_at'], name='events_even_sent_at_4bbe3e_idx')],
                'unique_together': {('rsvp', 'reminder_type')},
            },
        ),
    ]
