# Generated by Django 5.0.14 on 2025-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_add_event_reminder_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='background_color',
            field=models.CharField(blank=True, help_text='Custom background color in hex format, e.g., #1a1a2e (premium feature)', max_length=7),
        ),
        migrations.AddField(
            model_name='business',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Upload a custom background image (premium feature)', null=True, upload_to='business_backgrounds/'),
        ),
        migrations.AddField(
            model_name='business',
            name='background_overlay_opacity',
            field=models.IntegerField(default=0, help_text='Overlay opacity (0-100) for better text readability over background images (premium feature)'),
        ),
        migrations.AddField(
            model_name='business',
            name='events_per_page',
            field=models.IntegerField(choices=[(6, '6 events'), (12, '12 events'), (24, '24 events')], default=12, help_text='Number of events to display per page (premium feature)'),
        ),
        migrations.AddField(
            model_name='business',
            name='header_banner',
            field=models.ImageField(blank=True, help_text='Banner image displayed at top of business page (premium feature)', null=True, upload_to='business_banners/'),
        ),
        migrations.AddField(
            model_name='business',
            name='hide_contact_info',
            field=models.BooleanField(default=False, help_text='Hide email and phone from public page (premium feature)'),
        ),
        migrations.AddField(
            model_name='business',
            name='hide_past_events',
            field=models.BooleanField(default=False, help_text='Only show upcoming events, hide past events (premium feature)'),
        ),
        migrations.AddField(
            model_name='business',
            name='hide_social_links',
            field=models.BooleanField(default=False, help_text='Hide Instagram and TikTok links from public page (premium feature)'),
        ),
        migrations.AddField(
            model_name='business',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Custom secondary/accent color for buttons and links, e.g., #3498db (premium feature)', max_length=7),
        ),
        migrations.AlterField(
            model_name='business',
            name='background_image_url',
            field=models.URLField(blank=True, help_text='URL for custom background image - alternative to upload (premium feature)'),
        ),
    ]
