# Generated by Django 5.0.14 on 2025-12-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_add_business_page_customizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the venue (e.g., 'Central Park', 'The Coffee Shop')", max_length=255)),
                ('address', models.CharField(help_text='Full address of the venue', max_length=500)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business that owns this venue', on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='events.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Select a saved venue to auto-populate location fields', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['business', 'name'], name='events_venu_busines_a0069a_idx'),
        ),
    ]
