# Generated by Django 5.0.14 on 2026-01-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_add_venue_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Instagram username (without @) for importing events', max_length=30, null=True),
        ),
    ]
