# Generated by Django 5.0.14 on 2026-01-20 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_add_business_instagram_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='cancellation_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Token for guest to cancel their RSVP securely', null=True),
        ),
    ]
