# Generated by Django 5.0.14 on 2026-01-20 05:04

from django.db import migrations
import uuid


def populate_cancellation_tokens(apps, schema_editor):
    """Populate cancellation_token for existing RSVPs that don't have one."""
    EventRSVP = apps.get_model('events', 'EventRSVP')
    for rsvp in EventRSVP.objects.filter(cancellation_token__isnull=True):
        rsvp.cancellation_token = uuid.uuid4()
        rsvp.save(update_fields=['cancellation_token'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - set all tokens to null."""
    EventRSVP = apps.get_model('events', 'EventRSVP')
    EventRSVP.objects.all().update(cancellation_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_add_rsvp_cancellation_token'),
    ]

    operations = [
        migrations.RunPython(populate_cancellation_tokens, reverse_populate),
    ]
