# Generated by Django 5.0.14 on 2025-11-15 15:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for this plan', max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID for this plan', max_length=255)),
                ('max_events_per_month', models.IntegerField(default=0, help_text='Maximum events allowed per month (0 = unlimited)')),
                ('custom_subdomain_enabled', models.BooleanField(default=False, help_text='Allow custom subdomain (e.g., business.popmap.co)')),
                ('featured_listing', models.BooleanField(default=False, help_text='Featured in search results and map')),
                ('analytics_enabled', models.BooleanField(default=False, help_text='Access to analytics dashboard')),
                ('priority_support', models.BooleanField(default=False, help_text='Priority customer support')),
                ('is_active', models.BooleanField(default=True, help_text='Is this plan available for new subscriptions?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(help_text='Stripe Payment Method ID (pm_...)', max_length=255, unique=True)),
                ('payment_method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('us_bank_account', 'US Bank Account')], default='card', max_length=20)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(help_text='Stripe Customer ID (cus_...)', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Customer',
                'verbose_name_plural': 'Stripe Customers',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(help_text='Stripe Subscription ID (sub_...)', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired')], default='incomplete', max_length=20)),
                ('current_period_start', models.DateTimeField(help_text='Start of current billing period')),
                ('current_period_end', models.DateTimeField(help_text='End of current billing period')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Whether subscription will cancel at period end')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When the subscription was canceled', null=True)),
                ('trial_start', models.DateTimeField(blank=True, help_text='Start of trial period', null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='End of trial period', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='billing_sub_user_id_fe5b98_idx'), models.Index(fields=['stripe_subscription_id'], name='billing_sub_stripe__abc269_idx')],
            },
        ),
    ]
