# Generated by Django 5.0.14 on 2025-11-20 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognito_sub', models.CharField(db_index=True, help_text="Cognito user's sub (subject) identifier", max_length=255, unique=True)),
                ('role', models.CharField(choices=[('business_owner', 'Business Owner'), ('attendee', 'Attendee')], default='attendee', help_text='User role: business owner or attendee', max_length=20)),
                ('identity_provider', models.CharField(blank=True, help_text='Identity provider used (Cognito, Facebook, Google)', max_length=50, null=True)),
                ('is_profile_complete', models.BooleanField(default=False, help_text='Whether user has completed their profile')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Whether user wants to receive email notifications')),
                ('event_reminder_enabled', models.BooleanField(default=True, help_text='Whether user wants event reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['cognito_sub'], name='authenticat_cognito_340d06_idx'), models.Index(fields=['role'], name='authenticat_role_4d1409_idx')],
            },
        ),
    ]
