# Generated by Django 5.0.14 on 2025-11-19 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0009_add_business_custom_subdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('dropdown', 'Dropdown')], default='text', max_length=20)),
                ('label', models.CharField(help_text='Field label shown to users', max_length=255)),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for input fields', max_length=255)),
                ('help_text', models.CharField(blank=True, help_text='Optional help text shown below the field', max_length=500)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this field must be filled out')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Option text shown to users', max_length=255)),
                ('value', models.CharField(help_text='Internal value stored when selected', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('field', models.ForeignKey(limit_choices_to={'field_type': 'dropdown'}, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.formfield')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this form (not shown to users)', max_length=255)),
                ('title', models.CharField(help_text='Form title shown to users', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description shown at top of form')),
                ('notification_email', models.EmailField(help_text='Email address to receive form submissions', max_length=254)),
                ('send_confirmation_to_submitter', models.BooleanField(default=False, help_text='Send confirmation email to person who submitted the form')),
                ('confirmation_message', models.TextField(blank=True, help_text='Custom message in confirmation email')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this form is accepting submissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business that owns this form template', on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='events.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_email', models.EmailField(blank=True, help_text='Email collected from form or user profile', max_length=254)),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether notification email was sent')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent', models.BooleanField(default=False, help_text='Whether confirmation email was sent to submitter')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of submitter', null=True)),
                ('event', models.ForeignKey(blank=True, help_text='Event this submission is related to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='events.event')),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formtemplate')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.formtemplate'),
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text="User's response to this field")),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.formfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.formsubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission', 'field'], name='forms_formr_submiss_d2dcbd_idx')],
                'unique_together': {('submission', 'field')},
            },
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['business', 'is_active'], name='forms_formt_busines_3e5c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form_template', 'submitted_at'], name='forms_forms_form_te_a69ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['event', 'submitted_at'], name='forms_forms_event_i_88dfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['user'], name='forms_forms_user_id_869736_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form_template', 'order'], name='forms_formf_form_te_44f55b_idx'),
        ),
    ]
